apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      cluster: standby
    includeSelectors: false

patches:
  - path: grafana-ingress-patch.yaml
    target:
      kind: Ingress
      name: grafana
