
[workers]
hot-worker1 ansible_host=3.235.95.58

[k8s_cluster:children]
workers

[k8s_cluster:vars]
cluster_name=hot
cluster_role=hot
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/ha-assignment
ansible_python_interpreter=/usr/bin/python3

[local]
localhost ansible_connection=local ansible_python_interpreter="{{ ansible_playbook_python }}"

[all:vars]
kube_context=hot

cluster_platform_kubelet_insecure_tls=false

cluster_platform_pin_ingress_nginx_to_control_plane=false
